rewrite deploy workflow for ubuntu-latest runner and remove LIB_ prefix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,31 +1,48 @@
-name: Deploy CORE
+name: Build and deploy JWizard CORE
 
 on:
   push:
     branches: [ "master" ]
 
-defaults:
-  run:
-    shell: bash
+env:
+  PM2_CORE_NAME: JWizardCore
+  SSH_HOST: ${{ secrets.SSH_HOST }}
+  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
+  SSH_PORT: ${{ secrets.SSH_PORT }}
+  SSH_KEY: ${{ secrets.SSH_KEY }}
+  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
 
 jobs:
   pre-build:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
 
     steps:
       - name: Stop existing process
-        run: |
-          pm2 stop /root/ecosystem.config.js --only ${{ vars.PM2_CORE_NAME }} --silent
-          pm2 save
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ env.SSH_HOST }}
+          username: ${{ env.SSH_USERNAME }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_KEY }}
+          passphrase: ${{ env.SSH_PASSPHRASE }}
+          script: ~/exec/process stop ${{ env.PM2_CORE_NAME }}
 
   build:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     needs: pre-build
-    env:
-      RUNNER_ROOT_DIR: ${{ secrets.GH_RUNNER_ROOT_DIR }}
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Determinate latest JWizard LIB release tag
+        id: lib-release
+        env:
+          API_URL: https://api.github.com/repos/${{ vars.GH_LIB_REPO }}/releases/latest
+        run: |
+          latest_tag=$(curl -s ${{ env.API_URL }} | jq -r '.tag_name') && \
+            [ "$latest_tag" != "null" ] && echo "tag=${latest_tag:1}" >> $GITHUB_OUTPUT || \
+            { echo "Error: Could not define latest tag."; exit 1; }
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -33,63 +50,86 @@ jobs:
           java-version: '17'
           distribution: 'adopt'
 
-      - name: Change wrapper permissions
-        run: chmod +x ./gradlew
-
-      - name: Clean build dir
-        run: ./gradlew clean --no-daemon
-
       - name: Determinate build version
-        id: sha
+        id: version
         run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+
+      - name: Clean build directory
+        run: ./gradlew clean --no-daemon
 
       - name: Package to JAR
         run: ./gradlew shadowJar --no-daemon
-
-      - name: Revoke Vault key
         env:
-          VAULT_ADDR=${{ secrets.GH_VAULT_ADDR }}
-          VAULT_TOKEN=${{ secrets.GH_VAULT_TOKEN }}
-        run: |
-          VAULT_CORE_TOKEN=$(grep '^ENV_CORE_VAULT_TOKEN=' $RUNNER_ROOT_DIR/.env | cut -d '=' -f 2-) && \
-            [ -n "VAULT_CORE_TOKEN" ] && \
-            vault token revoke $VAULT_CORE_TOKEN || echo "Token not exist."
+          JWIZARD_VERSION: ${{ steps.version.outputs.sha_short }}
+          JWIZARD_LIB_VERSION: ${{ steps.lib-release.outputs.tag }}
 
-      - name: Generate and export Vault key
-        id: vault-keygen
-        env:
-          VAULT_ADDR=${{ secrets.GH_VAULT_ADDR }}
-          VAULT_TOKEN=${{ secrets.GH_VAULT_TOKEN }}
-        run: |
-          JWIZARD_TOKEN=$(vault token create -policy=jwizard-readonly -ttl=30d -renewable=false --format=json | jq -r '.auth.client_token')
-          sed -i "s/^ENV_CORE_VAULT_TOKEN=.*$/ENV_CORE_VAULT_TOKEN=$JWIZARD_TOKEN/" $RUNNER_ROOT_DIR/.env
-          echo "::add-mask::$JWIZARD_TOKEN"
-          echo "vault_key=$JWIZARD_TOKEN" >> "$GITHUB_OUTPUT"
-
-      - name: Determinate deployment version
-        id: vars
-        run: |
-          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-
-      - name: Generate env file
-        env:
-          JWIZARD_CORE_VAULT_TOKEN=${{ steps.vault-keygen.outputs.vault_key }}
-          JWIZARD_CORE_BUILD_VERSION=${{ steps.vars.outputs.sha_short }}_${{ github.run_number }}
-          JWIZARD_CORE_VAULT_SERVER=${{ secrets.GH_VAULT_SERVER }}
-        run: ./gradlew createEnv --no-daemon
+      - name: Upload generated JAR artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: output-jar
+          path: .bin/jwizard-core.jar
 
   deploy:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     needs: build
+    env:
+      SERVER_OUTPUT: "/var/www/jwizard-core"
 
     steps:
-      - name: Move compiled JAR file
+      - name: Download generated JAR artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: output-jar
+
+      - name: Move files to server
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ env.SSH_HOST }}
+          username: ${{ env.SSH_USERNAME }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_KEY }}
+          passphrase: ${{ env.SSH_PASSPHRASE }}
+          source: "jwizard-core.jar"
+          target: ${{ env.SERVER_OUTPUT }}
+          rm: true
+
+      - name: Determinate build version and date
+        id: deployment
         run: |
-          rm -rf /var/www/jwizard-core/*
-          rm -rf /var/www/jwizard-core/{*,.[!.]*,..?*} 2> /dev/null
-          cp -rT .bin /var/www/jwizard-core
+          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          echo "build_date=$(date +'%Y-%m-%dT%H:%M:%S%z %Z')" >> $GITHUB_OUTPUT
+
+      - name: Determinate latest release tag
+        id: release
+        env:
+          API_URL: https://api.github.com/repos/${{ github.repository }}/releases/latest
+          DEFAULT: none
+        run: |
+          latest_tag=$(curl -s ${{ env.API_URL }} | jq -r '.tag_name // "${{ env.DEFAULT }}"')
+          echo "tag=$latest_tag" >> $GITHUB_ENV
+
+      - name: Re-create config file
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ env.SSH_HOST }}
+          username: ${{ env.SSH_USERNAME }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_KEY }}
+          passphrase: ${{ env.SSH_PASSPHRASE }}
+          script: ./make-conf ${{ env.SERVER_OUTPUT }} "${{ secrets.CONFIG_FILE_CONTENT }}" \
+            "JWIZARD_BUILD_VERSION=${{ steps.deployment.outputs.sha_short }}_${{ github.run_number }}" \
+            "JWIZARD_BUILD_DATE=${{ steps.deployment.outputs.build_date }}" \
+            "JWIZARD_LATEST_RELEASE_TAG=${{ steps.release.outputs.tag }}"
 
       - name: Start process
-        run: |
-          pm2 start /root/ecosystem.config.js --only ${{ vars.PM2_CORE_NAME }} --silent
-          pm2 save
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ env.SSH_HOST }}
+          username: ${{ env.SSH_USERNAME }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_KEY }}
+          passphrase: ${{ env.SSH_PASSPHRASE }}
+          script: ~/exec/process start ${{ env.PM2_CORE_NAME }}
